### ISSUE TITLE
How to use Buefy UI components

### ISSUE THREAD

**Issue by binler** [nuxt-community/adonuxt-template#49]
Hi, I want to use Buefy, I try config like nuxt.js but not working.
https://buefy.github.io
Please tell me!!!!!!

**Comment by jzucadi** [comment]
You need to add Buefy to your nuxt.js file. Load the CSS and JS files here so that they are available globally. Try something like this:

module.exports = {
  plugins: [
    '~plugins/vuetify.js'
  ],
  css: [
    '~assets/css/main.css',
  ],
  build: {
    vendor: ['vuetify'],
}

**Comment by binler** [comment]
Hi, @jzucadi 
plugins/vuetify.js . What is the contents of the file?
I try 
import Vue from 'vue'
import Buefy from 'buefy'
import 'buefy/lib/buefy.css'

Vue.use(Buefy)

But not working. huhuhuhu

**Comment by jzucadi** [comment]
My mistake, I was copying and pasting my personal file and forgot to edit out vueitfy. How it should look is:
`
module.exports = {
plugins: [
'~plugins/buefy.js'
],
`
and the buefy.js should look like: 
`
import Vue from 'vue';
import Buefy from 'buefy';
import 'buefy/lib/buefy.css';

Vue.use(Buefy);

`

**Comment by binler** [comment]
@jzucadi . Awsome!!!!!
Thank you very very much

**Comment by jzucadi** [comment]
no problem!
