### ISSUE TITLE
Api routing ?

### ISSUE THREAD

**Issue by ludovicvue** [nuxt-community/adonuxt-template#54]
Hello, I'm wondering what would be a good practice to define my API routes.

In route.js `Route.any('*', 'NuxtController.render')` serves the front-end then how would you proceed to define API routes ? Would you define a subdomain for the group of API routes in routes.js ?

Thank you very much for your help, can't wait to start exploring!

**Comment by alexchopin** [comment]
Hi @ludovicvue, 
You only need to add routes before Nuxt routes.
I would recommend to use [Route Groups](https://adonisjs.com/docs/3.2/routing#_route_groups) for your API URLs.

**Comment by ludovicvue** [comment]
@alexchopin thanks!
