### ISSUE TITLE
Getting config on the client side

### ISSUE THREAD

**Issue by stas-sl** [nuxt-community/adonuxt-template#55]
Hi, do you have ideas how to pass configuration settings from AdonisJS to the Nuxt/Vue side?

When I'm trying this from Nuxt app:
```
const config = use('Config')
```
I'm getting:
```
ReferenceError: use is not defined
```

**Comment by cawa-93** [comment]
Try this: https://nuxtjs.org/api/configuration-env/#the-env-property
