### ISSUE TITLE
Live Demo not working

### ISSUE THREAD

**Issue by moraleslevi** [nuxt-community/adonuxt-template#83]
The Live Demo listed in the documentation is not working:

https://ado.nuxtjs.org/

This kind of reflects poorly on the application itself and/or zeit.co.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/adonuxt-template/issues/c68">#c68</a>)</em></sub></div>

**Comment by moraleslevi** [comment]
This appears to be fixed now. Closing.

**Comment by blowsie** [comment]
Not working again.

**Comment by 174n** [comment]
It still doesn't work. Can someone fix it?

**Comment by wemersonrv** [comment]
Hi. Not working!
