### ISSUE TITLE
How to use the updated versions of adonis

### ISSUE THREAD

**Issue by hkmsadek** [nuxt-community/adonuxt-template#93]
It seems it downloads older packages of adonis. how can I use the updated versions of all adonis packages?

**Comment by fuxic** [comment]
npm update
or
change @adonisjs versions in "package.json" & then run "npm update"

**Comment by martip07** [comment]
But, is it safe to update adonis? Or does it break something?

**Comment by vaggelis2018** [comment]
https://adonisjs.com/docs/4.1/upgrade-guide

**Comment by hkmsadek** [comment]
it's working this way so closing it, thanks. so far so good
