### ISSUE TITLE
Connecting from other devices on local network

### ISSUE THREAD

**Issue by eromanov** [nuxt-community/adonuxt-template#95]
Hi guys, 

I'm running Adonuxt on Win 10, and I can't seem to get to connect to my app from other devices on the same network. I have tried multiple things (changing the host IP address in the .env file, adding connect() listener to server.js, mapping ports in my hosts file, etc - pretty much everything you'd do to get access to Express on local network), but no luck so far. Any ideas where I could be going wrong? 

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/adonuxt-template/issues/c76">#c76</a>)</em></sub></div>

**Comment by Skalv** [comment]
have you try `HOST=0.0.0.0` in .env ?

**Comment by eromanov** [comment]
@Skalv I have indeed, and also allowed all inbound/outbound TCP and UDP connections on the required port - still no luck... Firewall is also configured to allow connections for Node.js.  

I am circumventing the problem by using ngrok at the moment.

**Comment by jaybeemind** [comment]
In your .env file, try replacing **HOST=localhost** to **HOST=_(ip of your machine)_**.
Then access that IP from another device.

**Comment by michaeljakob** [comment]
It would be a really amazing feature if `nuxt dev` (or `yarn dev`) would display the actual IP.

**Comment by michaeljakob** [comment]
Solution: https://stackoverflow.com/questions/55236594/nuxtjs-expose-localhost-to-external-doesnt-work
