### ISSUE TITLE
How to use Models in Vue Files

### ISSUE THREAD

**Issue by emirhanengn** [nuxt-community/adonuxt-template#98]
Hello!

I want to use model in vue files. But it returns an empty string to me. How can I use this?

![adsiz](https://user-images.githubusercontent.com/21215832/38918286-16f69854-42a2-11e8-9539-f2831500a10d.png)

**Comment by Extarys** [comment]
Have you tried `console.log(Posts.all())` before your push to make sure there is some data returned?

**Comment by MitsuhaKitsune** [comment]
The model .all() return a promise, you should do the query like this:

<script>
const Posts = use('App/Models/Post');

export default {
  data() {
    return {
      posts: [],
    };
  },

  asyncData({ app, params }) {
    return Posts.all().then(res => {
      return { posts: res.rows };
    });
  }
}
</script>
